# Generated by Django 4.2.7 on 2024-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=50, verbose_name='union'),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name',
            field=models.CharField(max_length=50, verbose_name='upazila'),
        ),
    ]
