# Generated by Django 4.2.7 on 2024-12-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localgovt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('type', models.CharField(choices=[('union parishad', 'Union Parishad'), ('upazila parishad', 'Upazila Parishad'), ('zila parishad', 'Zila Parishad'), ('city corporation', 'City Corporation')], max_length=20, verbose_name='Type of Local Govt')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.district', verbose_name='district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.division', verbose_name='division')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.union', verbose_name='union')),
                ('upazila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.upazila', verbose_name='upazila')),
            ],
            options={
                'verbose_name': 'localgovt',
                'verbose_name_plural': 'localgovts',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='position')),
                ('areas', models.CharField(max_length=200, verbose_name='working areas')),
                ('start_at', models.DateField(verbose_name='working start date')),
                ('end_at', models.DateField(verbose_name='working end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('localgovt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='local_govt.localgovt', verbose_name='local govt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
    ]
