# Generated by Django 4.2.7 on 2024-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_govt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgovt',
            name='type',
            field=models.CharField(choices=[('union', 'Union'), ('upazila', 'Upazila'), ('district', 'District'), ('division', 'Division')], max_length=20, verbose_name='Type of Local Govt'),
        ),
    ]
