# Generated by Django 4.2.7 on 2025-01-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='mobile number'),
        ),
    ]
